pipeline:
  name: accounttemp
  identifier: accounttemp
  template:
    templateRef: account.tempacc
    versionLabel: 6.2.2
    templateInputs:
      variables:
        - name: test
          type: String
          value: <+input>
  tags: {}
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
