pipeline:
  name: gitconfig
  identifier: gitconfig
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag: ""
  stages:
    - stage:
        name: dep
        identifier: dep
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: canarysrv
          environment:
            environmentRef: ECS_INFRA
            serviceOverrideInputs:
              variables:
                - name: over
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ee
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          repotokenbitbucket
                          TARGET_SECRET="repotokenbitbucket"
                          echo <+secrets.getValue("$TARGET_SECRET")>
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - abhidelegate
                    includeInfraSelectors: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        strategy:
          matrix:
            browser:
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
              - chrome
              - safari
              - firefox
              - sfar
              - djbd
              - dfdf
              - djfnfd
              - jsdfnk
              - djsnfkd
              - dfkndfk
              - jdnfjd
              - fnjn
              - jdnffj
              - kfdnfgk
              - ksdnfkf
              - sdnfdk
            maxConcurrency: 10
            when:
              stageStatus: All
        when:
          pipelineStatus: All
    - stage:
        name: pr
        identifier: pr
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: testprgitops
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update Release Repo
                  identifier: updateReleaseRepo
                  timeout: 10m
                  spec:
                    variables: []
                    prTitle: testpr
            rollbackSteps: []
          environment:
            environmentRef: ECS_INFRA
            deployToAll: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: All
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: dfdrf
  properties:
    ci:
      codebase:
        connectorRef: account.AbhinandanGit
        repoName: BasicMean
        build: <+input>
