pipeline:
  name: gitconfig
  identifier: gitconfig
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: dep
        identifier: dep
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8new
          environment:
            environmentRef: K8Env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: K8INFRA
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hey"
                          exit 1
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - abhidelegate
                    includeInfraSelectors: false
                  timeout: 10m
                  strategy:
                    matrix:
                      browser:
                        - chrome
                        - safari
                        - firefox
                        - sfar
                      maxConcurrency: 1
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>
