pipeline:
  name: inpuset
  identifier: inpuset
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo Y2QwNGM2MmI2YTRhMzdhMGQ4MWJkNjJlMTFlMmUwZjM=
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
