pipeline:
  name: inpuset
  identifier: inpuset
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8service
          environment:
            environmentRef: test12
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: test=test
                    environmentVariables: []
                    outputVariables:
                      - name: test
                        type: String
                        value: test
                  timeout: 10m
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  spec:
                    url: https://www.google.com/
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                  timeout: 10s
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.deploy.spec.execution.steps.ShellScript_1.output.outputVariables.test>
                          echo <+pipeline.stages.deploy.spec.execution.steps.Http_1.output.status>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>
