pipeline:
  name: inpuset
  identifier: inpuset
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: bluegreenservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: test12
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+stage.identifier>
                          exit 1
                    environmentVariables: []
                    outputVariables:
                      - name: test
                        type: String
                        value: test
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.deploy.spec.execution.steps.ShellScript_1.output.outputVariables.test>
                          echo <+pipeline.stages.deploy.spec.execution.steps.Http_1.output.status>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  when:
                    stageStatus: All
                    condition: <+stage.identifier>=="deploy"
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>.allowedValues(ddd,fdkfd,dfkfnld)
    - name: dknfdk
      type: String
      description: ""
      required: false
      value: <+input>.allowedValues(dmndk,djf;d,dfjbf)
