pipeline:
  name: inpuset
  identifier: inpuset
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: ex
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  spec:
                    url: https://orion-preprod.cloudtrust.rocks/iam/aws/oidc/addprovider
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                  timeout: 10s
        tags: {}
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>
