pipeline:
  name: inpuset
  identifier: inpuset
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo Y2QwNGM2MmI2YTRhMzdhMGQ4MWJkNjJlMTFlMmUwZjM=
                          echo <+secrets.getValue("pattoken")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: shell
                  identifier: shell
                  template:
                    templateRef: account.shell3
                    versionLabel: "1.0"
        tags: {}
    - stage:
        name: custom2
        identifier: custom2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
