pipeline:
  name: pipe1
  identifier: pipe1
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: name
        identifier: name
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: dc
              - step:
                  name: "n "
                  identifier: "n"
                  template:
                    templateRef: account.SEAL_AppSec_Scan_Step_Template
                    versionLabel: "1.2"
                    gitBranch: ParasharAbhi007-patch-1
                    templateInputs:
                      type: Run
                      spec:
                        image: <+input>.default("artifed.transunion.com/infosec-docker-dev-local/cxone-scanner:alma-1.0.2")
                        outputVariables:
                          - name: test
                            type: String
                            value: <+input>
                          - name: test2
                            type: String
                            value: <+input>
                          - name: test3
                            type: String
                            value: <+input>
