pipeline:
  name: pipe1234
  identifier: pipe1234
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: terst
        identifier: terst
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+<+variable.<+stage.variables.serverList>>.split(",")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  strategy:
                    repeat:
                      items: <+<+variable.<+stage.variables.serverList>>.split(",")>
        tags: {}
        variables:
          - name: serverList
            type: String
            description: ""
            required: false
            value: dev_windowsServers
    - stage:
        name: nws
        identifier: nws
        description: ""
        type: Pipeline
        spec:
          org: AbhiOrg
          pipeline: k8bluegreen
          project: CSETest1
          inputs:
            identifier: k8bluegreen
            stages:
              - stage:
                  identifier: bluegreendeploy
                  type: Deployment
                  spec:
                    serviceConfig:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          manifests:
                            - manifest:
                                identifier: manifest
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Github
                                    spec:
                                      branch: <+input>
                          artifacts:
                            primary:
                              type: ArtifactoryRegistry
                              spec:
                                tag: <+input>
                    infrastructure:
                      environmentRef: <+input>
            variables:
              - name: artifact
                type: String
                value: <+input>
    - stage:
        name: wsdfg
        identifier: wsdfg
        tags: {}
        template:
          templateRef: customstage
          versionLabel: "2"
          templateInputs:
            type: Custom
            spec:
              environment:
                infrastructureDefinitions:
                  - identifier: ee
                    inputs:
                      identifier: ee
                      type: KubernetesDirect
                      spec:
                        namespace: <+input>
            variables:
              - name: test
                type: String
                value: <+input>.default(test)
