pipeline:
  name: pipe1234
  identifier: pipe1234
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: terst
        identifier: terst
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: "echo <+ <+pipeline.branch> == \"main\" ? \"prod\" : <+pipeline.branch> == \"pre-prod\" ? \"preprod\" : \"dev\" >"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
