pipeline:
  name: test
  identifier: test
  projectIdentifier: Git_Exp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script
                  identifier: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "test"
                          exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
        variables:
          - name: test
            type: String
            description: ""
            value: <+input>
