pipeline:
  name: test123
  identifier: tester
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.AbhinandanGit
        repoName: charts
        build: <+input>
  stages:
    - stage:
        name: gf
        identifier: gf
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo hello
